### ISSUE TITLE
Option to exclude `site-packages` from python path

### ISSUE THREAD

**Issue by jmfederico** [frostming/pdm#100] opened 2020-04-10 20:39 UTC
PEP 582, as it is today only adds `__pypackages__` to the list of discovery paths. This might lead to the usage of globally installed packages by mistake.

I think it would be very useful if it were possible to remove global python paths on a per project basis. Maybe a flag on the pyproject.toml file.

Assuming a project in **/Users/foo/projects/bar** on macOS using python3.8 installed using official installers:

- Current path list
    ```python
    ['',
     '/Users/foo/projects/bar/pdm/__pypackages__/3.8/lib',
     '/Users/foo/projects/bar/pdm',
     '/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',
     '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8',
     '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload',
     '/Users/foo/Library/Python/3.8/lib/python/site-packages',
     '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages'
    ]
    ```

- Suggested path list
    ```python
    ['',
     '/Users/foo/projects/bar/pdm/__pypackages__/3.8/lib',
     '/Users/foo/projects/bar/pdm',
     '/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',
     '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8',
     '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload',
    ]
    ```

Is this something that you are open to?

**Comment by frostming** [comment] 2020-04-11 05:15
The behavior should affect two places:

1. `pdm run`
2. The entry point scripts under `__pypacakges__/X.Y/bin`

While we can provide an option in the first situation, we can't make this behavior as **optional** in the second situation.
So I would like to disable site-packages by default, any concern? @jmfederico

**Comment by jmfederico** [comment] 2020-04-11 06:54
@frostming it works for me. I do think that having system wide packages available with locally installed packages is a recipe for disaster.

**Comment by frostming** [comment] 2020-04-11 14:00
Still waiting for the CI to pass(something is going wrong with GitHub actions), the next release should come out in the next 2 days after the PR is merged.

**Closed** 2020-04-11 14:47 UTC
Labels: enhancement

**Comment by frostming** [comment] 2022-07-08 10:19
@mgzenitech If you use `pdm run`, they are excluded *by default*, and we offer an option to include them, but if you use the global PEP 582, they are *always* included.

**Comment by mgzenitech** [comment] 2022-07-08 10:47
Hi @frostming !
I haven't enabled PEP 582 globally (did not add anything to rc files from `pdm --pep582`). Also as you can see I am setting my own PYTHONPATH from .env file
`PYTHONPATH=lib/python:__pypackages__/3.9/lib`

**Comment by frostming** [comment] 2022-07-08 10:49
@mgzenitech The PYTHONPATH looks super weird to me.

I never have to set it like that. for example `__pypackages__/3.9/lib` will be auto-added when `pdm run`.

**Comment by mgzenitech** [comment] 2022-07-08 10:51
@frostming `__pypackages__/3.9/lib` is added only if you are **not using any additional paths** (in my case I need to add `lib/python` via env variable)

**Comment by frostming** [comment] 2022-07-08 10:52
@mgzenitech >  is added only if you are not using any additional paths

That is not correct, why do you think so?

**Comment by mgzenitech** [comment] 2022-07-08 10:54
because I have tried it and it didn't add `__pypackages__/3.9/lib`. Initially I've tried this in my `.env` file:
```
PYTHONPATH=lib/python
PYTHONDONTWRITEBYTECODE=1
```

And not packages from `__pypackages__/3.9/lib` could be imported

**Comment by frostming** [comment] 2022-07-08 10:58
i might know why, you are using a venv Python. check it by 'pdm info', the packages path shouldnt be empty @mgzenitech

**Comment by mgzenitech** [comment] 2022-07-08 12:13
@frostming 
```
➜  infra-terraform git:(pdm) ✗ pdm info
PDM version:        1.15.4
Python Interpreter: /home/mariusg/.pyenv/versions/3.9.9/bin/python3.9 (3.9)
Project Root:       /home/mariusg/Documents/Projects/infra-terraform
Project Packages:   /home/mariusg/Documents/Projects/infra-terraform/__pypackages__/3.9
```

**Comment by frostming** [comment] 2022-07-08 12:45
@mgzenitech Can you make it a minimal reproducible example? Preferably a Docker image. There are so many possible interferences, the local files, pyenv, env vars, etc. It's not clear which one is the critical factor. Users are responsible to diagnose the issue themselves.

**Comment by frostming** [comment] 2022-07-08 13:19
@mgzenitech it is handled in #1211

**Comment by mgzenitech** [comment] 2022-07-08 13:24
@frostming superb!
