### ISSUE TITLE
ValueError: '.*' not allowed for '>=' constraints

### ISSUE THREAD

**Issue by pawamoy** [frostming/pdm#249] opened 2021-02-04 17:18 UTC
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Run `pdm add -d package` 😕 ?

## Actual behavior

At some point in the resolution process I get this error:

```
======== Ending round 37 ========
Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/distlib/metadata.py", line 675, in __init__
    self._data = json.loads(data)
  File "/home/user/.basher-packages/pyenv/pyenv/versions/3.8.6/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/user/.basher-packages/pyenv/pyenv/versions/3.8.6/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/user/.basher-packages/pyenv/pyenv/versions/3.8.6/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 73, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 112, in main
    raise err.with_traceback(traceback)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 108, in main
    f(options.project, options)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/actions.py", line 163, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/actions.py", line 68, in do_lock
    mapping, dependencies, summaries = resolve(
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/resolver/core.py", line 135, in resolve
    result = resolver.resolve(requirements)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/resolvelib/resolvers.py", line 347, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/resolver/providers.py", line 74, in get_dependencies
    deps, requires_python, summary = self.repository.get_dependencies(candidate)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/repositories.py", line 64, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/repositories.py", line 30, in wrapper
    result = func(self, candidate)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/repositories.py", line 141, in _get_dependencies_from_metadata
    deps = candidate.get_dependencies_from_metadata()
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/candidates.py", line 189, in get_dependencies_from_metadata
    metadata = self.get_metadata()
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/candidates.py", line 156, in get_metadata
    self.metadata = self.wheel.metadata
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/distlib/util.py", line 446, in __get__
    value = self.func(obj)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/distlib/wheel.py", line 237, in metadata
    result = Metadata(fileobj=wf)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/distlib/metadata.py", line 684, in __init__
    self._legacy = LegacyMetadata(fileobj=StringIO(data),
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/distlib/metadata.py", line 259, in __init__
    self.read_file(fileobj)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/distlib/metadata.py", line 352, in read_file
    self.set(field, values)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/distlib/metadata.py", line 451, in set
    if not scheme.is_valid_matcher(v.split(';')[0]):
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/distlib/version.py", line 703, in is_valid_matcher
    self.matcher(s)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/distlib/version.py", line 115, in __init__
    raise ValueError('\'.*\' not allowed for '
ValueError: '.*' not allowed for '>=' constraints
```

## Expected behavior

No errors 😕 ?

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.2.0.post1                                                           
Python Interpreter: /home/user/.basher-packages/pyenv/pyenv/shims/python (3.6.12)
Project Root:       /home/user/data/dev/project                       
{
  "implementation_name": "cpython",
  "implementation_version": "3.6.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "3.10.0-862.6.3.el7.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Jun 15 17:57:37 EDT 2018",
  "python_full_version": "3.6.12",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.6",
  "sys_platform": "linux"
}
```

**Comment by pawamoy** [comment] 2021-02-04 17:24
Could be related to #130, I'll try to narrow it down.

**Comment by frostming** [comment] 2021-02-09 02:24
What package did you add? The README of `package` says "DON’T INSTALL THIS PACKAGE (package)!!!"

**Comment by frostming** [comment] 2021-02-09 02:56
Duplicate of #130 , close it now

**Closed by frostming** 2021-02-09 02:56 UTC
Labels: bug

**Comment by pawamoy** [comment] 2021-02-09 08:39
It was an in-house package, not available on pypi. I didn't use any wildcard (`.*`) it it so it mush have come from one of its dependencies.

**Comment by frostming** [comment] 2021-02-09 08:40
Thank you for clarifying, would you please try the latest release to see if the bug is gone?

**Comment by pawamoy** [comment] 2021-02-09 08:54
I haven't been able to replicate with master or 1.3.0 versions 🙂
